# À propos des auteurs {#auteurs .unnumbered}

[**Samuel Foucher**](https://www.usherbrooke.ca/recherche/fr/specialistes/details/samuel.foucher) est professeur au [Département de géomatique appliquée](https://www.usherbrooke.ca/geomatique/) de l'[Université de Sherbrooke](https://www.usherbrooke.ca/). Il y enseigne aux [programmes de 1^er^ et 2^e^ cycles de géomatique](https://www.usherbrooke.ca/geomatique/etudes/programmes) les cours *Traitement numérique des images de télédétection*, *Base de données géospatiales* et *Apprentissage profond appliqué à l'observation de la Terre*. Ses intérêts de recherche portent sur le traitement d'images et l'application de l'IA aux données géospatiales.

[**Mélanie Trudel**](https://www.usherbrooke.ca/recherche/fr/specialistes/details/melanie.trudel) est professeure au [Département de génie civil et de génie du bâtiment](https://www.usherbrooke.ca/genie/civil/) de la Faculté de génie de l'[Université de Sherbrooke](https://www.usherbrooke.ca/). Elle détient un doctorat en génie civil de l'École de technologie supérieure et une maîtrise en télédétection de l'Université de Sherbrooke. Ses intérêts de recherche portent sur la télédétection appliquée aux ressources en eau, ainsi que sur la modélisation hydrologique et hydraulique.

[**Gabriela Siles**](https://www.ffgg.ulaval.ca/faculte/departement-des-sciences-geomatiques/personnel-enseignant/gabriela-siles) est professeure adjointe au [Département des sciences géomatiques](https://www.ffgg.ulaval.ca/faculte/departement-des-sciences-geomatiques/) de l'[Université Laval](https://www.ulaval.ca/). Elle détient un doctorat en ingénierie de la *Technische Universität Braunschweig* (Allemagne), un diplôme d'ingénieure en géodésie et géophysique de l'*Universidad Nacional de Tucumán* (Argentine), et a réalisé un stage postdoctoral en télédétection et géomatique à l'Université de Sherbrooke. Ses expertises couvrent la télédétection et le traitement d'images, l'acquisition de données géospatiales et hydrospatiales, ainsi que l'analyse et la modélisation spatiales appliquées aux ressources en eau. Elle est membre de l'équipe scientifique de la mission SWOT.

[**Victoria Litalien**](https://www.usherbrooke.ca/genie/civil/) est professionnelle de recherche au [Département de génie civil et de génie du bâtiment](https://www.usherbrooke.ca/genie/civil/) de l'[Université de Sherbrooke](https://www.usherbrooke.ca/). Elle détient une maîtrise en géomatique appliquée et télédétection de l'Université de Sherbrooke. Ses travaux portent sur la télédétection, les ressources en eau et le suivi du couvert de glace des rivières.
